version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(name)s - %(message)s'
  
  colored:
    (): 'colorlog.ColoredFormatter'
    format: '%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(name)s%(reset)s - %(message)s'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red,bg_white

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  performance:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  voidlight_markitdown:
    level: DEBUG
    handlers: [console, file_debug, file_error]
    propagate: false
  
  voidlight_markitdown.converters:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false
  
  voidlight_markitdown.korean:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false
  
  voidlight_markitdown.performance:
    level: INFO
    handlers: [performance]
    propagate: false
  
  voidlight_markitdown_mcp:
    level: DEBUG
    handlers: [console, file_debug, file_error]
    propagate: false

root:
  level: INFO
  handlers: [console, file_debug]