apiVersion: v1
kind: Service
metadata:
  name: markitdown
  namespace: markitdown
  labels:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: markitdown-mcp
  namespace: markitdown
  labels:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: mcp-server
spec:
  type: ClusterIP
  ports:
  - name: mcp
    port: 3000
    targetPort: mcp
    protocol: TCP
  selector:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: mcp-server
---
apiVersion: v1
kind: Service
metadata:
  name: markitdown-redis
  namespace: markitdown
  labels:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: markitdown
    app.kubernetes.io/component: redis